---
# Source: graylog/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  labels:
    helm.sh/chart: graylog-1.6.6
    app.kubernetes.io/name: graylog
    app.kubernetes.io/instance: "graylog"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/version: "3.1"
    app.kubernetes.io/component: "web"
  name: graylog-web
  namespace: graylog
spec:
  tls:
  - hosts:
    - it-graylog.cp.lsst.org
    secretName: graylog-tls
  rules:
  - host: it-graylog.cp.lsst.org
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: graylog-web
              port: 
                name: graylog
